# Generated by Django 5.0.4 on 2024-11-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0004_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='Announce_authorId',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='Reports_authorId',
        ),
    ]
