# Generated by Django 5.1.3 on 2024-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0005_remove_announcements_announce_authorid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Room_propertyId',
        ),
        migrations.AddField(
            model_name='room',
            name='Room_details',
            field=models.TextField(default='No details available.'),
            preserve_default=False,
        ),
    ]
