# Generated by Django 5.1.3 on 2024-11-25 14:28

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0006_remove_room_room_propertyid_room_room_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
